[Desktop Entry]
Name=Software Updates
Name[ast]=Anovamientos de software
Name[ca]=Actualitzacions de programari
Name[ca@valencia]=Actualitzacions de programari
Name[cs]=Aktualizace software
Name[da]=Softwareopdateringer
Name[de]=Softwareaktualisierungen
Name[en_GB]=Software Updates
Name[es]=Actualizaciones de software
Name[fi]=Ohjelmistopäivitykset
Name[gl]=Actualizacións de software
Name[it]=Aggiornamenti software
Name[lt]=Programų atnaujinimai
Name[nl]=Software bijwerken
Name[nn]=Programoppdateringar
Name[pl]=Uaktualnienia oprogramowania
Name[pt]=Actualizações de Aplicações
Name[pt_BR]=Atualização de aplicativos
Name[ru]=Обновления программ
Name[sk]=Aktualizácie softvéru
Name[sv]=Uppdateringar av programvara
Name[tr]=Yazılım Güncellemeleri
Name[uk]=Оновлення програм
Name[x-test]=xxSoftware Updatesxx
Name[zh_CN]=软件更新

Comment=Get software updates
Comment[ast]=Consigue anovamientos de software
Comment[ca]=Obtén les actualitzacions de programari
Comment[ca@valencia]=Obtén les actualitzacions de programari
Comment[cs]=Získejte aktualizace software
Comment[da]=Hent softwareopdateringer
Comment[de]=Softwareaktualisierungen beziehen
Comment[en_GB]=Get software updates
Comment[es]=Obtener actualizaciones de software
Comment[fi]=Nouda ohjelmistopäivitykset
Comment[gl]=Obteña actualizacións de software.
Comment[it]=Scarica gli aggiornamenti del software
Comment[lt]=Parsisiųsti programų atnaujinimus
Comment[nl]=Elementen voor software bijwerken ophalen
Comment[nn]=Hent program­oppdateringar
Comment[pl]=Pobiera uaktualnienia oprogramowania
Comment[pt]=Obter actualizações das aplicações
Comment[pt_BR]=Obter a atualização de aplicativos
Comment[ru]=Обновления программного обеспечения
Comment[sk]=Získať aktualizácie softvéru
Comment[sv]=Hämta uppdateringar av programvara
Comment[tr]=Yazılım güncellemelerini al
Comment[uk]=Отримання оновлень програм
Comment[x-test]=xxGet software updatesxx
Comment[zh_CN]=获取软件更新

Icon=system-software-update
Type=Service
X-KDE-ServiceTypes=Plasma/Applet

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/main.qml

X-Plasma-NotificationArea=true

X-KDE-PluginInfo-Name=org.kde.plasma.pkupdates
X-KDE-PluginInfo-Category=System Information
X-KDE-PluginInfo-Author=Lukáš Tinkl
X-KDE-PluginInfo-Email=lukas@kde.org
X-KDE-PluginInfo-Version=@PROJECT_VERSION@
X-KDE-PluginInfo-Website=https://phabricator.kde.org/source/plasma-pk-updates/
X-KDE-PluginInfo-License=GPL2
X-KDE-PluginInfo-EnabledByDefault=true
