[Desktop Entry]
Name=Software Updates
Name[az]=Proqram Təminatı Yenilənmələri
Name[ca]=Actualitzacions de programari
Name[ca@valencia]=Actualitzacions de programari
Name[cs]=Aktualizace software
Name[da]=Softwareopdateringer
Name[de]=Softwareaktualisierungen
Name[en_GB]=Software Updates
Name[es]=Actualizaciones de software
Name[et]=Tarkvarauuendused
Name[eu]=Software eguneratzeak
Name[fi]=Ohjelmistopäivitykset
Name[fr]=Mises à jour des logiciels
Name[gl]=Actualizacións de software
Name[hu]=Szoftverfrissítések
Name[id]=Pembaruan Perangkat Lunak
Name[it]=Aggiornamenti software
Name[ko]=소프트웨어 업데이트
Name[lt]=Programinės įrangos atnaujinimai
Name[nl]=Elementen voor software bijwerken
Name[nn]=Programoppdateringar
Name[pa]=ਸਾਫਟਵੇਅਰ ਅੱਪਡੇਟ ਹਨ
Name[pl]=Uaktualnienia oprogramowania
Name[pt]=Actualizações de Aplicações
Name[pt_BR]=Atualização de aplicativos
Name[ro]=Actualizări de programe
Name[ru]=Обновления программ
Name[sk]=Aktualizácie softvéru
Name[sl]=Programske posodobitve
Name[sv]=Uppdateringar av programvara
Name[tg]=Навсозиҳои нармафзор
Name[tr]=Yazılım Güncellemeleri
Name[uk]=Оновлення програм
Name[x-test]=xxSoftware Updatesxx
Name[zh_CN]=软件更新
Name[zh_TW]=軟體更新

Comment=Get software updates
Comment[az]=Proqram təminatı yenilənmələrini alın
Comment[ca]=Obtén les actualitzacions de programari
Comment[ca@valencia]=Obtén les actualitzacions de programari
Comment[cs]=Získejte aktualizace software
Comment[da]=Hent softwareopdateringer
Comment[de]=Softwareaktualisierungen beziehen
Comment[en_GB]=Get software updates
Comment[es]=Obtener actualizaciones de software
Comment[et]=Tarkvarauuenduste hankimine
Comment[eu]=Lortu software eguneratzeak
Comment[fi]=Nouda ohjelmistopäivitykset
Comment[fr]=Télécharger les mises à jour des logiciels
Comment[gl]=Obteña actualizacións de software.
Comment[hu]=Szoftverfrissítések letöltése
Comment[id]=Dapatkan pembaruan perangkat lunak
Comment[it]=Scarica gli aggiornamenti del software
Comment[ko]=소프트웨어 업데이트 가져오기
Comment[lt]=Gauti programinės įrangos atnaujinimus
Comment[nl]=Elementen voor software bijwerken ophalen
Comment[nn]=Hent program­oppdateringar
Comment[pa]=ਸਾਫਟਵੇਅਰ ਅੱਪਡੇਟ ਲਵੋ
Comment[pl]=Pobiera uaktualnienia oprogramowania
Comment[pt]=Obter actualizações das aplicações
Comment[pt_BR]=Obter a atualização de aplicativos
Comment[ro]=Obține actualizări de programe
Comment[ru]=Обновления программного обеспечения
Comment[sk]=Získať aktualizácie softvéru
Comment[sl]=Pridobi programske posodobitve
Comment[sv]=Hämta uppdateringar av programvara
Comment[tg]=Гирифтани навсозиҳои нармафзор
Comment[tr]=Yazılım güncellemelerini al
Comment[uk]=Отримання оновлень програм
Comment[x-test]=xxGet software updatesxx
Comment[zh_CN]=获取软件更新
Comment[zh_TW]=取得軟體更新

Icon=system-software-update
Type=Service
X-KDE-ServiceTypes=Plasma/Applet

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/main.qml

X-Plasma-NotificationArea=true

X-KDE-PluginInfo-Name=org.kde.plasma.pkupdates
X-KDE-PluginInfo-Category=System Information
X-KDE-PluginInfo-Author=Lukáš Tinkl
X-KDE-PluginInfo-Email=lukas@kde.org
X-KDE-PluginInfo-Version=@PROJECT_VERSION@
X-KDE-PluginInfo-Website=https://phabricator.kde.org/source/plasma-pk-updates/
X-KDE-PluginInfo-License=GPL2
X-KDE-PluginInfo-EnabledByDefault=true
